/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class KalkulatorSederhana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KalkulatorSederhana.class.getName());
    
    /**
     * Creates new form KalkulatorSederhana
     */
    String angka;
    double jumlah;
    double bil1;
    double bil2;
    int pilih;
    
    public KalkulatorSederhana() {
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputAngka = new javax.swing.JTextField();
        delButton = new javax.swing.JButton();
        persenButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        number7Button = new javax.swing.JButton();
        number8Button = new javax.swing.JButton();
        number9Button = new javax.swing.JButton();
        timesButton = new javax.swing.JButton();
        number4Button = new javax.swing.JButton();
        number5Button = new javax.swing.JButton();
        number6Button = new javax.swing.JButton();
        number1Button = new javax.swing.JButton();
        number2Button = new javax.swing.JButton();
        number3Button = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();
        number0Button = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        clrButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(82, 8, 33));

        inputAngka.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        inputAngka.setForeground(new java.awt.Color(153, 153, 153));
        inputAngka.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputAngka.setText("0");
        inputAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAngkaActionPerformed(evt);
            }
        });

        delButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delButton.setText("DEL");
        delButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        persenButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        persenButton.setText("%");
        persenButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        persenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenButtonActionPerformed(evt);
            }
        });

        divideButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        divideButton.setText("/");
        divideButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        number7Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number7Button.setText("7");
        number7Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ButtonActionPerformed(evt);
            }
        });

        number8Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number8Button.setText("8");
        number8Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ButtonActionPerformed(evt);
            }
        });

        number9Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number9Button.setText("9");
        number9Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ButtonActionPerformed(evt);
            }
        });

        timesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        timesButton.setText("*");
        timesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesButtonActionPerformed(evt);
            }
        });

        number4Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number4Button.setText("4");
        number4Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ButtonActionPerformed(evt);
            }
        });

        number5Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number5Button.setText("5");
        number5Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ButtonActionPerformed(evt);
            }
        });

        number6Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number6Button.setText("6");
        number6Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ButtonActionPerformed(evt);
            }
        });

        number1Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number1Button.setText("1");
        number1Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ButtonActionPerformed(evt);
            }
        });

        number2Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number2Button.setText("2");
        number2Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ButtonActionPerformed(evt);
            }
        });

        number3Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number3Button.setText("3");
        number3Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ButtonActionPerformed(evt);
            }
        });

        minusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        minusButton.setText("-");
        minusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        plusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        plusButton.setText("+");
        plusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        decimalButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        decimalButton.setText(".");
        decimalButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        decimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalButtonActionPerformed(evt);
            }
        });

        number0Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number0Button.setText("0");
        number0Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        number0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ButtonActionPerformed(evt);
            }
        });

        equalsButton.setBackground(new java.awt.Color(255, 0, 102));
        equalsButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        equalsButton.setText("=");
        equalsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        clrButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clrButton.setText("clr");
        clrButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputAngka)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(number0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(number2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(number5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(number7Button, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(clrButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(delButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number8Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(persenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(number3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(timesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(equalsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(inputAngka, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAngkaActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        if (angka.length() > 0) {
        angka = angka.substring(0, angka.length() - 1);
    }
        if (angka.isEmpty()) {
        inputAngka.setText("0");
        } 
        else {
        inputAngka.setText(angka);
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void persenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenButtonActionPerformed
        if (!angka.isEmpty()) {
            bil1 = Double.parseDouble(angka);
            jumlah = bil1 / 100;
            angka = Double.toString(jumlah);
            inputAngka.setText(angka);
        }
    }//GEN-LAST:event_persenButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        if (!angka.isEmpty()) {
            bil1 = Double.parseDouble(angka);
            inputAngka.setText("/");
            angka = "";
            pilih = 4; 
        }
    }//GEN-LAST:event_divideButtonActionPerformed

    private void number7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ButtonActionPerformed
        angka += "7";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number7ButtonActionPerformed

    private void number8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ButtonActionPerformed
        angka += "8";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number8ButtonActionPerformed

    private void number9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ButtonActionPerformed
        angka += "9";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number9ButtonActionPerformed

    private void timesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesButtonActionPerformed
        if (!angka.isEmpty()) {
            bil1 = Double.parseDouble(angka);
            inputAngka.setText("*");
            angka = "";
            pilih = 3; 
        }
    }//GEN-LAST:event_timesButtonActionPerformed

    private void number4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ButtonActionPerformed
        angka += "4";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number4ButtonActionPerformed

    private void number5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ButtonActionPerformed
        angka += "5";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number5ButtonActionPerformed

    private void number6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ButtonActionPerformed
        angka += "6";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number6ButtonActionPerformed

    private void number1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ButtonActionPerformed
        angka += "1";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number1ButtonActionPerformed

    private void number2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ButtonActionPerformed
        angka += "2";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number2ButtonActionPerformed

    private void number3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ButtonActionPerformed
        angka += "3";
        inputAngka.setText(angka);
    }//GEN-LAST:event_number3ButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        if (!angka.isEmpty()) {
            bil1 = Double.parseDouble(angka);
            inputAngka.setText("-");
            angka = "";
            pilih = 2; 
        }
    }//GEN-LAST:event_minusButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        if (!angka.isEmpty()) {
            bil1 = Double.parseDouble(angka);
            inputAngka.setText("+");
            angka = "";
            pilih = 1; 
        }
    }//GEN-LAST:event_plusButtonActionPerformed

    private void decimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalButtonActionPerformed
        if (!angka.contains(".")) {
            if (angka.isEmpty()) {
                angka = "0.";
            } else {
                angka += ".";
            }
        }
        inputAngka.setText(angka);
    }//GEN-LAST:event_decimalButtonActionPerformed

    private void number0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ButtonActionPerformed
        if (!angka.equals("") && !angka.equals("0")) {
            angka += "0";
        } else if (angka.equals("")) {
             angka = "0"; 
        }
        inputAngka.setText(angka);
    }//GEN-LAST:event_number0ButtonActionPerformed

    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
        if (!angka.isEmpty() && pilih != 0) {
            bil2 = Double.parseDouble(angka);

            switch (pilih) {
                case 1: 
                    jumlah = bil1 + bil2;
                    break;
                case 2: 
                    jumlah = bil1 - bil2;
                    break;
                case 3: 
                    jumlah = bil1 * bil2;
                    break;
                case 4: 
                    if (bil2 != 0) {
                        jumlah = bil1 / bil2;
                    } else {
                        inputAngka.setText("Error: Divide by 0");
                        angka = "";
                        pilih = 0;
                        return; 
                    }
                    break;
                default:
                    break;
            }

            if (jumlah == (long) jumlah) {
                angka = String.valueOf((long) jumlah);
            } 
            else {
                angka = String.valueOf(jumlah);
            }

            inputAngka.setText(angka);
            bil1 = jumlah; 
            angka = "";
            pilih = 0; 
        }
    }//GEN-LAST:event_equalsButtonActionPerformed

    private void clrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrButtonActionPerformed
        inputAngka.setText("0");
        bil1 = 0.0;
        bil2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_clrButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KalkulatorSederhana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clrButton;
    private javax.swing.JButton decimalButton;
    private javax.swing.JButton delButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton equalsButton;
    private javax.swing.JTextField inputAngka;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton number0Button;
    private javax.swing.JButton number1Button;
    private javax.swing.JButton number2Button;
    private javax.swing.JButton number3Button;
    private javax.swing.JButton number4Button;
    private javax.swing.JButton number5Button;
    private javax.swing.JButton number6Button;
    private javax.swing.JButton number7Button;
    private javax.swing.JButton number8Button;
    private javax.swing.JButton number9Button;
    private javax.swing.JButton persenButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton timesButton;
    // End of variables declaration//GEN-END:variables
}
